### ISSUE TITLE
[frictionless] aggiungere il delimiter ad un datapackage

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/tansignari#249]
Sera!

Mi piacerebbe aggiungere le informazioni relative al delimiter
```yaml
dialect:
  delimiter: ;
```
in un datapackage (precisamente "Tabular Data Resource") senza manualmente copiare e incollare queste due righe.

A quanto ho capito non c'è un flag di `frictionless describe` che permette di "aggiungere automaticamente le info relative al delimiter" ma esiste l'opzione `--dialect` che tuttavia non riesco a far funzionare ;)

Se lancio:
```
frictionless describe --help
```

ottengo
```
Usage: frictionless describe [OPTIONS] [SOURCE]...

Arguments:
  [SOURCE]...  Data source [default: stdin]

Options:
  --dialect TEXT                  An inline JSON object or a path to a JSON
                                  file that provides the dialect
                                  (configuration for the parser)
```

Un paio di domande:
1. ma come faccio a creare "An inline JSON object or a path to a JSON file that provides the dialect"? Devo farlo a manina? 
2. Qual è la sintassi completa del comando describe col flag --dialect? Forse `frictionless describe --dialect dialectinfo.json data.csv`?

**Comment by aborruso** [comment]
Caro @dennisangemi ,
quando il delimiter non è presente, si dà per scontato che sia quello di default. che per il dialetto CSV è la `,`.

Infatti se hai in input

```
a;b
3;t
4;v
``` 

e dai `frictionless describe --type "package"  input_01.csv`, ottieni

```yaml
resources:
  - name: input_01
    type: table
    path: input_01.csv
    scheme: file
    format: csv
    encoding: utf-8
    mediatype: text/csv
    dialect:
      csv:
        delimiter: ;
    schema:
      fields:
        - name: a
          type: integer
        - name: b
          type: string
```

Se invece hai un CSV con separator `,` non hai nulla, e se non hai nulla il separatore è la `,`.

Se ne vuoi forzare comunque la scrittura, a partire ad esempio da 

```
a,b
3,t
4,v
```

devi definirlo come opzione di dialetto

```
frictionless describe --type "package" --dialect '{"csv": {"delimiter": ","}}' input.csv
```

che ti darà

```yaml
resources:
  - name: input
    type: table
    path: input.csv
    scheme: file
    format: csv
    encoding: utf-8
    mediatype: text/csv
    dialect:
      csv:
        delimiter: ','
    schema:
      fields:
        - name: a
          type: integer
        - name: b
          type: string
```
